name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@5dafb461cea1f8b296d89297dc6de7bd0891f0d2 # v0.44.2
    with:
      image: ghcr.io/radiorabe/mariadb
      name: mariadb
      display-name: RaBe MariaDB in UBI9
      tags: minimal rhel9 ubi9 rabe mariadb
      cosign-image-skip-regexp: quay.io/sclorg/mariadb-105-c9s
  release-mkdocs:
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@b37e51397726092d8462a2a9b676ea5a5e3a8deb # v0.44.1
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@b37e51397726092d8462a2a9b676ea5a5e3a8deb # v0.44.1
